export const MODIFIER_CATEGORIES = [
    {
        id: "action",
        label: "Subject Action",
        options: [
            "Playing Music",
            "Running",
            "Dancing",
            "Flying",
            "Fighting",
            "Meditating",
            "Laughing",
            "Crying",
            "Dancing in the Rain",
            "Reading a Book",
            "Exploring a Cave",
            "Cooking a Feast",
            "Climbing a Mountain",
            "Watching the Stars",
            "Walking along a Beach",
            "Painting a Masterpiece",
            "Gardening",
            "Sailing",
        ],
    },
    {
        id: "medium",
        label: "Medium",
        options: [
            "Photography",
            "Oil Painting",
            "3D Render",
            "Watercolor",
            "Sketch",
            "Digital Illustration",
            "Polaroid",
            "Anime",
            "Statue / Sculpture",
            "Claymation",
            "Pixel Art",
            "Comic Book",
            "Street Art / Graffiti",
        ],
    },
    {
        id: "style",
        label: "Art Style / Vibe",
        options: [
            "Cyberpunk",
            "Fantasy",
            "Minimalist",
            "Vaporwave",
            "Steampunk",
            "Surrealism",
            "Studio Ghibli",
            "Noir",
            "Bauhaus",
            "Ukiyo-e",
            "Pop Art",
            "Art Nouveau",
            "Impressionist",
            "Abstract Expressionism",
            "Renaissance",
            "Baroque",
        ],
    },
    {
        id: "lighting",
        label: "Lighting",
        options: [
            "Cinematic",
            "Golden Hour",
            "Volumetric Fog",
            "Studio Lighting",
            "Neon",
            "Bioluminescent",
            "Harsh Shadows",
            "Soft Glow",
            "Rim Lighting",
        ],
    },
    {
        id: "composition",
        label: "Framing / Composition",
        options: [
            "Rule of Thirds",
            "Bird's Eye View",
            "Low Angle",
            "Symmetrical",
            "Double Exposure",
            "Golden Ratio",
            "Panorama",
            "Macro",
            "Dutch Angle",
        ],
    },
    {
        id: "color",
        label: "Color Palette",
        options: [
            "Vibrant",
            "Monochrome",
            "Pastel",
            "Neon Pink & Blue",
            "Sepia",
            "High Contrast",
            "Muted Tones",
            "Earthy",
        ],
    },
    {
        id: "atmosphere",
        label: "Mood / Atmosphere",
        options: [
            "Ethereal",
            "Ominous",
            "Joyful",
            "Melancholy",
            "Nostalgic",
            "Dreamlike",
            "Chaotic",
            "Serene",
            "Epic",
        ],
    },
    {
        id: "magic",
        label: "Magic Words",
        options: [
            "Masterpiece",
            "Photorealistic",
            "Hyper-detailed",
            "8k Resolution",
            "Highly Commended",
            "Trending on ArtStation",
            "Intricate Detail",
            "Cinematic Detail",
            "Award Winning",
        ],
    },
    {
        id: "render",
        label: "Technical Render",
        options: [
            "Unreal Engine 5",
            "Lumen / Nanite",
            "Octane Render",
            "Redshift Render",
            "V-Ray",
            "Ray Tracing",
            "Global Illumination",
            "Physically Based Rendering",
            "Subsurface Scattering",
            "Ambient Occlusion",
            "Depth of Field",
            "Motion Blur",
            "Anamorphic Lens Flare",
            "High Fidelity / 8K",
        ],
    },
    {
        id: "environment",
        label: "Environment / Setting",
        options: [
            "During Golden Hour",
            "Under a Starry Night Sky",
            "In a Foggy Morning",
            "During a Thunderstorm",
            "Deep Space",
            "Lush Jungle",
            "Cybernetic Lab",
            "Ancient Temple Ruins",
            "In Autumn Bloom",
            "Under Northern Lights",
            "Winter Snowfall",
            "Abandoned Asylum",
            "Underwater Kingdom",
        ],
    },
];